"""start of seed

Revision ID: 9d128255e75e
Revises: 18136a430e6b
Create Date: 2024-02-15 15:41:47.637728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d128255e75e'
down_revision = '18136a430e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.add_column('recipes', sa.Column('image', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('ingredients', sa.JSON(), nullable=True))
    op.add_column('recipes', sa.Column('steps', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('users', '_password_hash')
    op.drop_column('recipes', 'steps')
    op.drop_column('recipes', 'ingredients')
    op.drop_column('recipes', 'image')
    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ingredients')
    )
    # ### end Alembic commands ###
